### ISSUE TITLE
Compilation errors on Android with Core 2.x

### ISSUE THREAD

**Issue by nirinchev** [realm/realm-object-store#526]
We get the following compilation errors on Android with Sync 1.x/Core 2.x. They were introduced with #512

```
jni/../src/object-store/src/list.cpp:189: error: undefined reference to 'unsigned int realm::Table::find_first<realm::BinaryData>(unsigned int, realm::BinaryData) const'
jni/../src/object-store/src/results.cpp:329: error: undefined reference to 'unsigned int realm::Table::find_first<realm::BinaryData>(unsigned int, realm::BinaryData) const'
```

**Comment by bdash** [comment]
It's hard to tell what the context of this error is. "undefined reference" makes it sound like a linker error,  in which case that be an issue with core's static library missing symbols rather an object store bug.

**Comment by nirinchev** [comment]
Correct - I imagine it's a problem that the `BinaryData` case hasn't been explicitly instantiated in Core: https://github.com/realm/realm-core/blob/master/src/realm/table.cpp#L3971, that has been exposed by #512 starting to use the generic.

**Comment by bdash** [comment]
I made a PR with the fix for this at the core level in realm/realm-core#2823. I'll talk to Core and Sync teams about getting these into releases as soon as is practical.

**Comment by bdash** [comment]
This was fixed by realm/realm-core#2823.
