### PR TITLE
Add should_compact_on_launch_function

### PR DESCRIPTION
**Pull request by jpsim**
needed for https://github.com/realm/realm-cocoa/issues/3289

interprocess tests will be done in cocoa PR

### CODE REVIEW

**Comment by jpsim** [comment]
In progress and not expected to pass CI because it uses unreleased core code from realm/realm-core#2547.

**Comment by jpsim** [comment]
Any ideas what could be causing the Windows errors on CI? /cc @fealebenpae

```
c:\jenkins\workspace\m_realm-object-store_pr-411-yftvqcze453b4hy4pypo7l2rhryp3nv3kxb3l5oegvwsl67xijcq\tests\util/any.hpp(29): error C2011: 'realm::util::Any': 'class' type redefinition [C:\jenkins\workspace\m_realm-object-store_PR-411-YFTVQCZE453B4HY4PYPO7L2RHRYP3NV3KXB3L5OEGVWSL67XIJCQ\tests\tests.vcxproj]
```

Stale build artifacts from a different job perhaps? `realm::util::Any` was touched in #410.

**Comment by jpsim** [comment]
This is ready for review now.

I don't understand the CI failures as they don't seem related to my changes. I skirted around the Windows compilation failure in 98ffce1 by disabling these changes from being visible to Windows targets, since I remembered that `compact()` isn't safe to call on Windows platforms _anyway_: https://github.com/realm/realm-core/blob/v2.6.0/src/realm/group_shared.hpp#L413-L414

**Comment by tgoyne** [comment]
The build errors reference `tests/util/any.hpp` which doesn't even exist in this branch (it was moved to a different place on master), which suggests it's building the wrong thing.

**Comment by jpsim** [comment]
d5cf683 appears to have resolved the CI issues.

**Comment by jpsim** [comment]
@tgoyne @austinzheng do your ✅ s from realm/realm-cocoa#4755 apply to this PR too?
